apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: nsenpc01 ##Database Root Password
      - name: MYSQL_DATABASE
        value: sen ##Database Host Name
      ports:
      - containerPort: 3306
