apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: nsen
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      ports:
        - containerPort: 3306
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pvc 
